# Results

## Overall Trend
//To-do: Modified Label\

```{r , echo=FALSE,fig.width=8, fig.height=6}

library(data.table)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
library(reshape2)

rate = fread("../ml-25m/ratings.csv")
movie = fread("../ml-25m/movies.csv")


rate = merge(rate, movie, by = c("movieId"), all.x = TRUE)


rate$date = as.POSIXct(rate$timestamp, origin="1970-01-01", tz="GMT")
rate$date = as.Date(rate$date, "GMT")

rate$year = format(rate$date, format = "%Y")
rate = rate %>% filter(year > 1995)
rate_count = rate %>% group_by(year) %>% summarise(count = n(), mean_score = mean(rating))

rate_count$count = rate_count$count/1000000
rate_cnt_gather = gather(rate_count, key = "name", value = "value", -year)

#scaleFactor <- max(rate_count$count) / max(rate_count$mean_score)
theme_update(plot.title = element_text(hjust = 0.5))
g = ggplot(rate_count) +
  geom_line(aes(x = year, y = count, group = 1)) +
  ggtitle("Rating Trend & Count Trend",) +
  labs (x = "Year", y = "Rate Count(1 million)/Per year") +
  theme_grey(12) +
  theme(legend.title = element_blank(), plot.title=element_text(hjust=0.5)) +
  scale_x_discrete(breaks = seq(1995, 2020, by = 2))


var_name <- c(
  'count'="Rate Number[M/year]",
  "mean_score"="Average Rating[/5]"
)

g = ggplot(rate_cnt_gather) +
  geom_line(aes(x = year, y = value, group = 1)) +
  ggtitle("Rating Trend & Count Trend",) +
  theme_grey(12) +
  theme(legend.title = element_blank(), plot.title=element_text(hjust=0.5)) +
  scale_x_discrete(breaks = seq(1995, 2020, by = 2)) +
    facet_grid(name~., labeller = as_labeller(var_name))
g


```


## Genre Exploration
//To-do: Modified Label\


```{r , echo=FALSE}

genres = rate %>% select(c("genres", "year", "rating")) %>% 
   mutate(genres =  strsplit(genres, split='|', fixed=TRUE)) %>%
   unnest(c(genres))
genres_cnt = genres %>% group_by(genres) %>% summarise(count = n()/1000000, mean_score = mean(rating)) %>%
  arrange(-count)

ggplot(data=genres_cnt, aes(x=count, y=reorder(genres, count))) +
    geom_bar(stat="identity") + 
  scale_y_discrete("Genre name", expand=c(0,0)) + 
  scale_x_continuous("Total Rate Count[Million]")

rm(genres);invisible(gc())

```


## Popular Genre Year Analysis

```{r, echo = FALSE,fig.width=6, fig.height=4}


cross_func <- function(category, c_list){
  cnt = 0
  for(c in c_list){
    if(grepl(category, c)){
      cnt = cnt + 1
    }
  }
  return(cnt)
}




genres = rate %>% select(c("genres", "year", "rating")) %>% 
   mutate(genres =  strsplit(genres,split='|', fixed=TRUE)) %>%
   unnest(c(genres))

genres_cnt = genres %>% group_by(genres) %>% summarise(count = n(), mean_score = mean(rating)) %>%
  arrange(-count)

top_genres = genres_cnt[1:5, ]
selected_genres = c(top_genres$genres)

genres = genres %>% filter(genres %in% selected_genres)

genres_year = genres %>% group_by(year, genres) %>% summarise(count = n(), mean_score = mean(rating))

genres_year = genres_year[order(genres_year$genres, genres_year$year),]

ggplot(genres_year,) +
    geom_line( aes(year, count, color = genres, group = genres)) + 
  theme_grey(10) +
  theme(legend.title = element_blank()) +
  scale_x_discrete(breaks = seq(1995, 2020, by = 3))


```

## Overlap for popular genres

```{r, echo = FALSE}

for(c in selected_genres){
  movie[,paste(c)] = mapply(grepl, movie$genres, c)
}

movie$cnt = rowSums(movie[,c("Drama","Comedy","Action","Thriller", "Adventure")])


movie$cat = case_when(movie$cnt == 0 ~ "None of popular genre", 
          movie$cnt == 1 ~ "contain 1 famous genre", 
          movie$cnt == 2 ~ "contain 2 famous genre", 
          movie$cnt >= 3 ~ "contain > 3 famous genre", 
          TRUE ~ "NA")

movie_overlap = movie %>% group_by(cat) %>% summarise(count = n())


# Data transformation
movie_overlap <- movie %>% 
  group_by(cat) %>% # Variable to be transformed
  count() %>% 
  ungroup() %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

ggplot(movie_overlap, aes(x = "", y = perc, fill = cat)) +
  geom_col(color = "black") +
  geom_label(aes(label = labels), color = c("white", "white", "black", "white"),
            position = position_stack(vjust = 0.5),
            show.legend = FALSE) +
  guides(fill = guide_legend(title = "Answer")) +
  scale_fill_viridis_d() +
  coord_polar(theta = "y") + 
  theme_void()
```


## Popular Movie in Most popular genres

```{r, echo = FALSE}

genres = rate %>% select(c("genres", "year", "rating", "title")) %>% 
   mutate(genres =  strsplit(genres,split='|', fixed=TRUE)) %>%
   unnest(c(genres))

genres_cnt = genres %>% group_by(genres) %>% 
  summarise(count = n(), mean_score = mean(rating)) %>%
  arrange(-count)

top_genre_data = genres_cnt[1, ]
top_genres =  c(top_genre_data$genres)

genres = genres %>% filter(genres %in% top_genres)

movie_cnt = genres  %>% group_by(title) %>% summarise(count = n(), mean_score = mean(rating))

movie_cnt = movie_cnt[order(movie_cnt$count, decreasing = TRUE),]

movie_cnt = movie_cnt[1:10, ]


ggplot(data=movie_cnt, aes(x=count, y=reorder(title, count))) +
    geom_bar(stat="identity") + 
  scale_y_discrete("Movie name", expand=c(0,0)) + 
  scale_x_continuous("Total Rate Count")
```


## Trend of The most popular Movie 

```{r, echo = FALSE,fig.width=8, fig.height=4}

genres = rate %>% select(c("genres", "year", "rating", "title")) %>% 
   mutate(genres =  strsplit(genres,split='|', fixed=TRUE)) %>%
   unnest(c(genres))

genres_cnt = genres %>% group_by(genres) %>% 
  summarise(count = n(), mean_score = mean(rating)) %>%
  arrange(-count)

top_genres = genres_cnt[1, ]
top_genre =  c(top_genres$genres)

genres = genres %>% filter(genres %in% top_genre)


movie_cnt = genres  %>% group_by(title) %>% summarise(count = n(), mean_score = mean(rating))

movie_cnt = movie_cnt[order(movie_cnt$count, decreasing = TRUE),]

movie_cnt = movie_cnt[1:5, ]

movie_trend = genres %>% filter(title %in% c(movie_cnt$title))


movie_year = movie_trend %>% group_by(year, title) %>% summarise(count = n(), mean_score = mean(rating))

movie_year = movie_year[order(movie_year$title, movie_year$year),]

ggplot(movie_year,) +
    geom_line( aes(year, mean_score, color = title, group = title)) + 
  theme_grey(10) +
  theme(legend.title = element_blank()) +
  scale_x_discrete(breaks = seq(1995, 2020, by = 3))

```

## Aluvial for famous movies


```{r, echo = FALSE,fig.width=8, fig.height=4}

movie_name = c("Forrest Gump (1994)", "Shawshank Redemption, The (1994)", 
  "Pulp Fiction (1994)" , "Schindler's List (1993)","Braveheart (1995)")

rate_f = rate %>% filter(title %in% movie_name)
```

